### ISSUE TITLE
Splitting a long string causes Sink to crash

### ISSUE THREAD

**Issue by pmarflee** [voidqk/sink#46]
**str.split** causes Sink to crash when presented with the following input:

```
var input = "6592822488931338589815525425236818285229555616392928433262436847386544514648645288129834834862363847542262953164877694234514375164927616649264122487182321437459646851966649732474925353281699895326824852555747127547527163197544539468632369858413232684269835288817735678173986264554586412678364433327621627496939956645283712453265255261565511586373551439198276373843771249563722914847255524452675842558622845416218195374459386785618255129831539984559644185369543662821311686162137672168266152494656448824719791398797359326412235723234585539515385352426579831251943911197862994974133738196775618715739412713224837531544346114877971977411275354168752719858889347588136787894798476123335894514342411742111135337286449968879251481449757294167363867119927811513529711239534914119292833111624483472466781475951494348516125474142532923858941279569675445694654355314925386833175795464912974865287564866767924677333599828829875283753669783176288899797691713766199641716546284841387455733132519649365113182432238477673375234793394595435816924453585513973119548841577126141962776649294322189695375451743747581241922657947182232454611837512564776273929815169367899818698892234618847815155578736875295629917247977658723868641411493551796998791839776335793682643551875947346347344695869874564432566956882395424267187552799458352121248147371938943799995158617871393289534789214852747976587432857675156884837634687257363975437535621197887877326295229195663235129213398178282549432599455965759999159247295857366485345759516622427833518837458236123723353817444545271644684925297477149298484753858863551357266259935298184325926848958828192317538375317946457985874965434486829387647425222952585293626473351211161684297351932771462665621764392833122236577353669215833721772482863775629244619639234636853267934895783891823877845198326665728659328729472456175285229681244974389248235457688922179237895954959228638193933854787917647154837695422429184757725387589969781672596568421191236374563718951738499591454571728641951699981615249635314789251239677393251756396"

say (str.split input, "")
```

Smaller strings are split correctly, so I'm guessing it's something to do with the length of the string.

**Comment by velipso** [comment]
This is a fantastic bug -- this will lead to a few changes to the API.  Thanks for reporting, I'll have to work on this in my spare time!

It looks like the issue is that the string table is being reallocated underneath some cached values that expect the string table to stay in a constant place.

**Comment by pmarflee** [comment]
Thanks for replying.  I'm using Sink to work through some of [last year's Advent of Code problems](http://adventofcode.com/2017), where the puzzle inputs are usually long strings.  I can work around the problem by creating an empty list of the expected size, looping through the characters in the string and updating each element in the list with the numeric representation of the character.  For instance:

```
def parse input
  var numbers = list.new &input, 0 
  for var i: range &input
    numbers[i] = +input[i]
  end
  return numbers
end
```

Does this look like a good approach?

**Comment by velipso** [comment]
Ya that looks fine -- I'll try and get a fix out for the first bug, hopefully I can get that done today.

**Comment by velipso** [comment]
Ok, I pushed changes that *should* fix this issue, when you have a chance can you test out the new code?

Not sure how you're using sink, but I also published new binaries (beta2), linked on the main README page.

**Comment by pmarflee** [comment]
I'm using the Windows binary.  I've tested my code against the beta2 release and can confirm that the problem has been fixed.
