### ISSUE TITLE
Lexical scoping bug with loops when variable declaration occurs before assignment

### ISSUE THREAD

**Issue by pmarflee** [voidqk/sink#47]
There appears to be a problem with lexical scoping in relation to loop blocks.  Consider the following program:

```
def calculate rows
    var sum = 0
    for var row: rows
        var largest, smallest
        say "begin loop: largest = $largest, smallest = $smallest"
        for var number: row
            if largest == nil || number > largest
                largest = number
            end
            if smallest == nil || number < smallest
                smallest = number
            end
        end
        say "end loop: largest = $largest, smallest = $smallest"
        sum += largest - smallest
    end
    return sum
end

say "result: ${calculate { { 5, 1, 9, 5}, {7, 5, 3}, {2, 4, 6, 8} }}" # returns 24, but should be 18
```

At the beginning of the first iteration of the outer loop, _largest_ and _smallest_ are both _nil_.  With each iteration of the outer loop, I would expect _largest_ and _smallest_ to be _nil_.  However, what happens instead is that with subsequent iterations of the loop, they retain their values from the previous iteration.  I can work around this by assigning _nil_ to these variables when they are declared, but it doesn't seem like I should have to do this.

**Comment by velipso** [comment]
Verified with test program:

```
for: range 2
    var a
    say a
    a = 1
end
```

Should output two `nil`s, but outputs `nil` then `1`.

Likely won't fix this for some time, I don't have much free time and this one seems minor.

Thank you for reporting though, it's very helpful -- I will keep this ticket open.

**Comment by pmarflee** [comment]
No worries. It's an easy one to work around.

**Comment by velipso** [comment]
https://github.com/voidqk/sink/commit/30bbfd34dcbe86efa0df9de431fa5b989231a7ad fixes this issue

However, I haven't created new binaries, so the problem will persist in them until beta 3 is released (unknown time).

**Comment by velipso** [comment]
FYI @pmarflee just released beta3 binaries
